truncate table products;

INSERT INTO products(code, name, description, image_url, price) VALUES
('P100','The Hunger Games','Winning will make you famous. Losing means certain death...','https://images.gr-assets.com/books/1447303603l/2767052.jpg',34.0),
('P101','To Kill a Mockingbird','The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it...','https://images.gr-assets.com/books/1361975680l/2657.jpg',45.4),
('P102','The Chronicles of Narnia','Journeys to the end of the world, fantastic creatures, and epic battles between good and evil.','https://images.gr-assets.com/books/1449868701l/11127.jpg',44.5),
('P103','Gone with the Wind', 'Gone with the Wind is a novel written by Margaret Mitchell, first published in 1936.', 'https://images.gr-assets.com/books/1328025229l/18405.jpg',44.5),
('P104','The Fault in Our Stars','Despite the tumor-shrinking medical miracle that has bought her a few years, Hazel has never been anything but terminal.','https://images.gr-assets.com/books/1360206420l/11870085.jpg',14.5),
('P105','The Giving Tree','Once there was a tree...and she loved a little boy.','https://images.gr-assets.com/books/1174210942l/370493.jpg',32.0),
('P106','The Da Vinci Code','An ingenious code hidden in the works of Leonardo da Vinci. A desperate race through the cathedrals and castles of Europe','https://images.gr-assets.com/books/1303252999l/968.jpg',14.5),
('P107','The Alchemist','Paulo Coelho''s masterpiece tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure','https://images.gr-assets.com/books/1483412266l/865.jpg',12.0),
('P108','Charlotte''s Web','This beloved book by E. B. White, author of Stuart Little and The Trumpet of the Swan, is a classic of children''s literature','https://images.gr-assets.com/books/1439632243l/24178.jpg',14.0),
('P109','The Little Prince','Moral allegory and spiritual autobiography, The Little Prince is the most translated book in the French language.','https://images.gr-assets.com/books/1367545443l/157993.jpg',16.5),
('P110','A Thousand Splendid Suns','A Thousand Splendid Suns is a breathtaking story set against the volatile events of Afghanistan''s last thirty years.','https://images.gr-assets.com/books/1345958969l/128029.jpg',15.5),
('P111','A Game of Thrones','Here is the first volume in George R. R. Martin’s magnificent cycle of novels that includes A Clash of Kings and A Storm of Swords.','https://images.gr-assets.com/books/1436732693l/13496.jpg',32.0),
('P112','The Book Thief','Nazi Germany. Death has never been busier, and will be busier still. By her brother''s graveside, Liesel''s life is changed when she picks up a single object.','https://images.gr-assets.com/books/1522157426l/19063.jpg',30.0),
('P113','One Flew Over the Cuckoo''s Nest','Tyrannical Nurse Ratched rules her ward in an Oregon State mental hospital with a strict and unbending routine.','https://images.gr-assets.com/books/1516211014l/332613.jpg',23.0),
('P114','Fifty Shades of Grey','When literature student Anastasia Steele goes to interview young entrepreneur Christian Grey, she encounters a man who is beautiful, brilliant, and intimidating.','https://images.gr-assets.com/books/1385207843l/10818853.jpg',27.0),
('P115','The Catcher in the Rye','A story about adolescent Holden Caulfield''s disillusionment and rebellion against the adult world.','https://images.gr-assets.com/books/1398034300l/5107.jpg',19.0),
('P116','Pride and Prejudice','A classic novel of manners, morality, education, and marriage in early 19th-century England.','https://images.gr-assets.com/books/1320399351l/1885.jpg',22.5),
('P117','The Great Gatsby','F. Scott Fitzgerald’s novel of the Jazz Age captures the decadence and excess of 1920s America.','https://images.gr-assets.com/books/1490528560l/4671.jpg',18.75),
('P118','1984','A dystopian novel set in a totalitarian regime that uses surveillance, censorship, and control.','https://images.gr-assets.com/books/1532714506l/40961427.jpg',21.0),
('P119','Brave New World','A prophetic novel depicting a futuristic society driven by technology, consumption, and control.','https://images.gr-assets.com/books/1437234892l/5129.jpg',20.0),
('P120','Moby-Dick','Herman Melville''s epic tale of obsession and revenge between Captain Ahab and the white whale.','https://images.gr-assets.com/books/1327940656l/153747.jpg',25.0),
('P121','The Kite Runner','A story of friendship and redemption set in Afghanistan, spanning from the 1970s to modern times.','https://images.gr-assets.com/books/1579031894l/77203.jpg',16.0),
('P122','Crime and Punishment','Dostoevsky’s psychological masterpiece about guilt, morality, and redemption.','https://images.gr-assets.com/books/1382846449l/7144.jpg',24.5),
('P123','The Lord of the Rings','An epic fantasy adventure about the struggle to destroy the One Ring.','https://images.gr-assets.com/books/1566425108l/33.jpg',40.0),
('P124','Harry Potter and the Sorcerer''s Stone','The first book in J.K. Rowling''s beloved series about the young wizard Harry Potter.','https://images.gr-assets.com/books/1474154022l/3.jpg',28.0),
('P125','War and Peace','Leo Tolstoy’s monumental novel set during Napoleon’s invasion of Russia.','https://images.gr-assets.com/books/1413215930l/656.jpg',35.0),
('P126','Jane Eyre','Charlotte Brontë’s gothic romance and a critique of class and gender roles.','https://images.gr-assets.com/books/1327867269l/10210.jpg',19.5),
('P127','Wuthering Heights','A haunting tale of passion and revenge on the Yorkshire moors.','https://images.gr-assets.com/books/1388212715l/6185.jpg',21.0),
('P128','Anna Karenina','Tolstoy’s tragic story of love and betrayal in imperial Russia.','https://images.gr-assets.com/books/1391046413l/15823480.jpg',29.0),
('P129','Don Quixote','Cervantes’ classic tale of a knight and his loyal squire Sancho Panza.','https://images.gr-assets.com/books/1387264893l/3836.jpg',26.0),
('P130','Frankenstein','Mary Shelley’s gothic masterpiece about creation and consequence.','https://images.gr-assets.com/books/1381512375l/18490.jpg',15.5),
('P131','Apple iPhone 14','Latest Apple smartphone with A15 Bionic chip, OLED display, and advanced cameras.','https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone14.jpg',999.0),
('P132','Samsung Galaxy S23','Flagship Android smartphone with Snapdragon processor and dynamic AMOLED screen.','https://images.samsung.com/galaxy-s23.jpg',899.0),
('P133','Dell XPS 13 Laptop','Ultra-slim laptop with Intel i7, 16GB RAM, 512GB SSD, and InfinityEdge display.','https://i.dell.com/sites/csimages/Master_Imagery/all/xps-13.jpg',1299.0),
('P134','Sony WH-1000XM5 Headphones','Noise-cancelling over-ear headphones with premium sound.','https://m.media-amazon.com/images/I/61vJtKbAssL._AC_SL1500_.jpg',349.0),
('P135','Apple MacBook Air M2','Lightweight laptop with Apple Silicon chip, Retina display, and all-day battery.','https://store.storeimages.cdn-apple.com/macbook-air-m2.jpg',1199.0),
('P136','Canon EOS 90D DSLR Camera','Professional camera with 32.5MP sensor and 4K video.','https://m.media-amazon.com/images/I/81U4cNSEegL._AC_SL1500_.jpg',1099.0),
('P137','Logitech MX Master 3 Mouse','Ergonomic wireless mouse with programmable buttons.','https://m.media-amazon.com/images/I/61ni3t1ryQL._AC_SL1500_.jpg',99.0),
('P138','Apple iPad Pro 12.9','Powerful tablet with M1 chip, Liquid Retina XDR display, and 5G support.','https://store.storeimages.cdn-apple.com/ipad-pro.jpg',1099.0),
('P139','Samsung 55\" 4K Smart TV','Ultra HD smart TV with HDR and streaming apps built-in.','https://images.samsung.com/4k-tv.jpg',699.0),
('P140','Nike Air Max 270 Sneakers','Stylish and comfortable sneakers with Air cushioning.','https://static.nike.com/air-max-270.jpg',150.0),
('P141','Adidas Ultraboost 22','High-performance running shoes with Boost midsole.','https://assets.adidas.com/ultraboost.jpg',180.0),
('P142','Levi''s 501 Jeans','Classic straight-fit denim jeans for everyday wear.','https://lsco.scene7.com/is/image/lsco/501-original-fit.jpg',65.0),
('P143','Puma Hoodie','Casual hoodie with soft fleece and adjustable hood.','https://images.puma.com/puma-hoodie.jpg',55.0),
('P144','Ray-Ban Aviator Sunglasses','Iconic aviator sunglasses with UV protection.','https://assets.ray-ban.com/aviator.jpg',160.0),
('P145','The North Face Jacket','Durable, waterproof outdoor jacket for all seasons.','https://www.thenorthface.com/jacket.jpg',220.0),
('P146','Zara Casual Shirt','Slim-fit casual cotton shirt for men.','https://static.zara.net/shirt.jpg',40.0),
('P147','H&M Summer Dress','Lightweight floral dress perfect for summer.','https://hm.com/summer-dress.jpg',35.0),
('P148','Under Armour T-Shirt','Performance t-shirt with sweat-wicking technology.','https://underarmour.scene7.com/tshirt.jpg',30.0),
('P149','Converse Chuck Taylor All Star','Classic canvas sneakers with rubber sole.','https://converse.com/chuck-taylor.jpg',60.0),
('P150','Gucci Leather Belt','Luxury leather belt with signature GG buckle.','https://gucci.com/leather-belt.jpg',350.0);
